---
# ./roles/common/tasks/apt.yml

- name: Apt tasks
  hosts: localhost

  tasks:

  - name: Patch packages
    apt:
      update_cache: yes
      cache_valid_time: 3600
      upgrade: dist
    tags:
      - update
    
  - name: Check if reboot required
    register: reboot_required_file
    stat: path=/var/run/reboot-required get_md5=no

  - include_tasks: reboot.yml
    when: reboot_required_file.exists

...
